-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."DanhGia"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID_SinhVien" integer NOT NULL,
    "YThucKyLuat_text" text COLLATE pg_catalog."default",
    "YThucKyLuat_number" numeric NOT NULL,
    "TuanThuThoiGian_text" text COLLATE pg_catalog."default",
    "TuanThuThoiGian_number" numeric NOT NULL,
    "KienThuc_text" text COLLATE pg_catalog."default",
    "KienThuc_numberr" numeric NOT NULL,
    "KyNangNghe_text" text COLLATE pg_catalog."default",
    "KyNangNghe_number" numeric NOT NULL,
    "KhaNangDocLap_text" text COLLATE pg_catalog."default",
    "KhaNangDocLap_number" numeric NOT NULL,
    "KhaNangNhom_text" text COLLATE pg_catalog."default",
    "KhaNangNhom_number" numeric NOT NULL,
    "KhaNangGiaiQuyetCongViec_text" text COLLATE pg_catalog."default",
    "KhaNangGiaiQuyetCongViec_number" numeric NOT NULL,
    "DanhGiaChung_number" numeric NOT NULL,
    "GhiChu" text COLLATE pg_catalog."default",
    CONSTRAINT "DanhGia_pkey" PRIMARY KEY ("ID")
);

COMMENT ON TABLE public."DanhGia"
    IS 'Danh sách đánh giá sinh viên';

CREATE TABLE IF NOT EXISTS public."DeTai"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Ten" text COLLATE pg_catalog."default" NOT NULL,
    "MoTa" text COLLATE pg_catalog."default",
    "isDeleted" boolean NOT NULL DEFAULT false,
    CONSTRAINT "DeTai_pkey" PRIMARY KEY ("ID")
);

COMMENT ON TABLE public."DeTai"
    IS 'Danh sách đề tài';

CREATE TABLE IF NOT EXISTS public."DiaChi"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "DiaChi" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "DiaChi_pkey" PRIMARY KEY ("ID")
);

COMMENT ON TABLE public."DiaChi"
    IS 'Danh sách địa chỉ Xã, Huyện, Tỉnh để gợi ý';

CREATE TABLE IF NOT EXISTS public."KyThucTap"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "NgayBatDau" date NOT NULL,
    "NgayKetThuc" date NOT NULL,
    "isDeleted" boolean NOT NULL DEFAULT false,
    CONSTRAINT "KyThucTap_pkey" PRIMARY KEY ("ID")
);

COMMENT ON TABLE public."KyThucTap"
    IS 'Danh sách kỳ thực tập';

CREATE TABLE IF NOT EXISTS public."Nganh"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Ten" text COLLATE pg_catalog."default" NOT NULL,
    "KyHieu" text COLLATE pg_catalog."default",
    CONSTRAINT "Nganh_pkey" PRIMARY KEY ("ID")
);

COMMENT ON TABLE public."Nganh"
    IS 'Danh sách ngành';

CREATE TABLE IF NOT EXISTS public."NguoiHuongDan"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "HoTen" text COLLATE pg_catalog."default" NOT NULL,
    "SDT" character varying(10) COLLATE pg_catalog."default",
    "Email" text COLLATE pg_catalog."default",
    "ChucDanh" text COLLATE pg_catalog."default",
    "Phong" text COLLATE pg_catalog."default",
    "Username" text COLLATE pg_catalog."default" NOT NULL,
    "Password" text COLLATE pg_catalog."default" NOT NULL,
    "Zalo" text COLLATE pg_catalog."default",
    "Facebook" text COLLATE pg_catalog."default",
    "Github" text COLLATE pg_catalog."default",
    "Avatar" text COLLATE pg_catalog."default",
    CONSTRAINT "NguoiHuongDan_pkey" PRIMARY KEY ("ID")
);

COMMENT ON TABLE public."NguoiHuongDan"
    IS 'Bảng danh sách người hướng dẫn';

CREATE TABLE IF NOT EXISTS public."NhomThucTap"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID_NguoiHuongDan" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID_KyThucTap" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ID_DeTai" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "isDeleted" boolean NOT NULL DEFAULT False,
    CONSTRAINT "NhomThucTap_pkey" PRIMARY KEY ("ID")
);

COMMENT ON TABLE public."NhomThucTap"
    IS 'Danh sách nhóm thực tập';

CREATE TABLE IF NOT EXISTS public."SinhVien"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "MSSV" character varying(10) COLLATE pg_catalog."default" NOT NULL,
    "HoTen" text COLLATE pg_catalog."default" NOT NULL,
    "GioiTinh" integer NOT NULL DEFAULT 1,
    "SDT" character varying(10) COLLATE pg_catalog."default" NOT NULL,
    "Email" text COLLATE pg_catalog."default",
    "DiaChi" integer NOT NULL,
    "MaLop" character varying(10) COLLATE pg_catalog."default" NOT NULL,
    "Truong" integer NOT NULL,
    "Nganh" integer NOT NULL,
    "Khoa" integer NOT NULL,
    "NhomThucTap" integer,
    PRIMARY KEY ("ID")
);

COMMENT ON TABLE public."SinhVien"
    IS 'Bảng danh sách sinh viên';

CREATE TABLE IF NOT EXISTS public."Truong"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Ten" text COLLATE pg_catalog."default" NOT NULL,
    "KyHieu" text COLLATE pg_catalog."default",
    CONSTRAINT "Truong_pkey" PRIMARY KEY ("ID")
);

COMMENT ON TABLE public."Truong"
    IS 'Danh sách trường';

ALTER TABLE IF EXISTS public."DanhGia"
    ADD FOREIGN KEY ("ID_SinhVien")
    REFERENCES public."SinhVien" ("ID") MATCH FULL
    ON UPDATE CASCADE
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."NhomThucTap"
    ADD FOREIGN KEY ("ID_DeTai")
    REFERENCES public."DeTai" ("ID") MATCH FULL
    ON UPDATE CASCADE
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."NhomThucTap"
    ADD FOREIGN KEY ("ID_KyThucTap")
    REFERENCES public."KyThucTap" ("ID") MATCH FULL
    ON UPDATE CASCADE
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."NhomThucTap"
    ADD FOREIGN KEY ("ID_NguoiHuongDan")
    REFERENCES public."NguoiHuongDan" ("ID") MATCH FULL
    ON UPDATE CASCADE
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SinhVien"
    ADD FOREIGN KEY ("Truong")
    REFERENCES public."Truong" ("ID") MATCH FULL
    ON UPDATE CASCADE
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SinhVien"
    ADD FOREIGN KEY ("Nganh")
    REFERENCES public."Nganh" ("ID") MATCH FULL
    ON UPDATE CASCADE
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SinhVien"
    ADD FOREIGN KEY ("DiaChi")
    REFERENCES public."DiaChi" ("ID") MATCH FULL
    ON UPDATE CASCADE
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SinhVien"
    ADD FOREIGN KEY ("NhomThucTap")
    REFERENCES public."NhomThucTap" ("ID") MATCH FULL
    ON UPDATE CASCADE
    ON DELETE NO ACTION
    NOT VALID;

END;